In [1]:
import torch
import numpy as np
import pickle

In [2]:
def make_chunks(mfccs, labels, window_size=64, stride=32):
    chunk = []
    chunk_labels = []
    for mfcc, label in zip(mfccs, labels):
        # (W - F + 2P)/S + 1
        for start in range(0, int((mfcc.shape[1] - window_size)/stride)+1): 
            chunk.append(mfcc[:, start * stride:(start * stride + window_size)])
            chunk_labels.append(label)
    return(chunk, chunk_labels)

train_Y, test_Y = pickle.load(open('train_labels.dump', 'rb'))
train_X = pickle.load(open('train_mfcc.dump', 'rb'))
test_X = pickle.load(open('test_mfcc.dump', 'rb'))
train_X, train_Y = make_chunks(train_X, train_Y)
test_X, test_Y = make_chunks(test_X, test_Y)


In [3]:
from torch.utils.data import Dataset, DataLoader
class MyDataset(Dataset):
    def __init__(self, data, label, transform=None):
        self.data = torch.from_numpy(np.array(data)).float()
        self.label = torch.from_numpy(np.array(label)).long()
        self.transform = transform
        
    def __getitem__(self, index:int):
        x = self.data[index]
        y = self.label[index]
        
        if self.transform:
            x = self.transform(x)
        
        return x[np.newaxis, ...], y
    
    def __len__(self):
        return len(self.data)

dataset = MyDataset(train_X, train_Y)
loader =  DataLoader(
    dataset,
    batch_size=32,
    shuffle=True,
    num_workers=8,
    pin_memory=torch.cuda.is_available()
)

#idx, (data, label) = next(enumerate(loader))
#print(data.shape)
#print(label)
for batch_idx, (data, target) in enumerate(loader):
    print('Batch idx {}, data shape {}, target shape {}'.format(batch_idx, data.shape, target.shape))

Batch idx 0, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 1, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 2, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 3, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 4, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 5, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 6, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 7, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 8, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 9, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 10, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 11, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Ba

Batch idx 328, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 329, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 330, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 331, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 332, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 333, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 334, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 335, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 336, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 337, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 338, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 339, data shape torch.Size([32, 1, 13, 64]), target sha

Batch idx 645, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 646, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 647, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 648, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 649, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 650, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 651, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 652, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 653, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 654, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 655, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 656, data shape torch.Size([32, 1, 13, 64]), target sha

Batch idx 975, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 976, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 977, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 978, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 979, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 980, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 981, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 982, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 983, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 984, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 985, data shape torch.Size([32, 1, 13, 64]), target shape torch.Size([32])
Batch idx 986, data shape torch.Size([32, 1, 13, 64]), target sha

In [4]:
import torchvision.models as models
resnet18 = models.resnet18()
model = torch.nn.Sequential(
    torch.nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, bias=False),
    torch.nn.BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True),
    torch.nn.ReLU(),
    torch.nn.MaxPool2d(kernel_size=(1,2)),
    
    torch.nn.Conv2d(32, 32, kernel_size=(2, 2), stride=(1, 1), padding=(1,1), bias=False),
    torch.nn.BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True),
    torch.nn.Conv2d(32, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1,1), bias=False),
    torch.nn.BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True),
    torch.nn.Conv2d(32, 64, kernel_size=(2, 2), stride=(1, 1), padding=(1,1), bias=False),
    torch.nn.BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True),
    torch.nn.ReLU(),

    torch.nn.Flatten(),
    torch.nn.Linear(
        in_features=7616,
        out_features=128
    ),
    torch.nn.Dropout(p=0.5),
    torch.nn.Linear(
        in_features=128,
        out_features=8
    ),
)
#print(model(data).shape)
#print(resnet18)

In [5]:
model = model.cuda()
optimizer = torch.optim.Adam(model.parameters())
criterion = torch.nn.CrossEntropyLoss()

for epoch in range(100):  # loop over the dataset multiple times
    running_loss = 0.0
    for i, data in enumerate(loader):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data
        inputs = inputs.cuda()
        labels = labels.cuda()
        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
    print('[%d, %5d] loss: %.3f' %(epoch + 1, i + 1, running_loss / 2000))
    running_loss = 0.0

[1,  1013] loss: 0.895
[2,  1013] loss: 0.797
[3,  1013] loss: 0.751
[4,  1013] loss: 0.711
[5,  1013] loss: 0.664
[6,  1013] loss: 0.621
[7,  1013] loss: 0.569
[8,  1013] loss: 0.526
[9,  1013] loss: 0.480
[10,  1013] loss: 0.439
[11,  1013] loss: 0.408
[12,  1013] loss: 0.377
[13,  1013] loss: 0.351
[14,  1013] loss: 0.327
[15,  1013] loss: 0.307
[16,  1013] loss: 0.287
[17,  1013] loss: 0.269
[18,  1013] loss: 0.258
[19,  1013] loss: 0.243
[20,  1013] loss: 0.230
[21,  1013] loss: 0.218
[22,  1013] loss: 0.208
[23,  1013] loss: 0.197
[24,  1013] loss: 0.193
[25,  1013] loss: 0.185
[26,  1013] loss: 0.180
[27,  1013] loss: 0.166
[28,  1013] loss: 0.164
[29,  1013] loss: 0.159
[30,  1013] loss: 0.153
[31,  1013] loss: 0.145
[32,  1013] loss: 0.138
[33,  1013] loss: 0.137
[34,  1013] loss: 0.133
[35,  1013] loss: 0.129
[36,  1013] loss: 0.124
[37,  1013] loss: 0.117
[38,  1013] loss: 0.121
[39,  1013] loss: 0.112
[40,  1013] loss: 0.111
[41,  1013] loss: 0.114
[42,  1013] loss: 0.107
[

In [18]:
test_X = np.array(test_X)
test_X_tensor = np.expand_dims(test_X, 1)
test_X_tensor = torch.from_numpy(test_X_tensor).float().cuda()
model.eval()
prediction = model(test_X_tensor)

RuntimeError: CUDA out of memory. Tried to allocate 240.00 MiB (GPU 0; 10.76 GiB total capacity; 9.15 GiB already allocated; 134.12 MiB free; 120.85 MiB cached)

In [17]:
prob = torch.nn.functional.softmax(prediction, dim=0)
final = torch.argmax(prob, dim=1).cpu().numpy()
print(final)
print(test_Y)
print(np.sum(np.equal(final, test_Y)) / len(test_Y))

[1 5 3 ... 6 1 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 

In [16]:
idx, (data, label) = next(enumerate(loader))
data = model(data.cuda())
prob = torch.nn.functional.softmax(data, dim=1)
final = torch.argmax(prob, dim=1).cpu().numpy()
label = label.numpy()
print(final)
print(label)
print(np.equal(final, label).sum() / len(label))

[1 5 0 0 3 6 2 0 0 3 0 0 4 7 6 2 0 7 0 0 2 1 0 2 3 3 5 0 2 0 1 3]
[1 5 0 0 3 6 2 0 0 3 0 0 4 7 6 2 0 7 0 6 2 1 0 2 3 3 5 0 2 0 1 3]
0.96875
